enable-magisk-update = true
parallel-jobs = 2
compression-level = 9
remove-rv-integrations-checks = true
rv-brand = "ReVanced ReX"

[YouTube]
enabled = true
app-name = "YT+++++"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
include-stock = true
excluded-patches = "'GmsCore support'"
patcher-args = """\
  -O 'packageName=app.revanced.ytplus' \
"""

[Spotify]
enabled = true
app-name = "Spotify"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ltd/spotify-music/"
build-mode = "both"
include-stock = true
# Pas de patch exclu, package + signature originaux
